# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteLista
PathDefault =  ..\Fontes
err         =  ..\Produtos
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Fontes

[Modulos]
TestLis
Lista

[BuildInicio]
/OUT:..\produtos\TesteLista.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
../objetos/ArcaboucoTeste.lib
../objetos/Lista.obj
[Fim]
