
[Diretorios]

Nome        =  TesteCircular
PathDefault =  ..\Fontes
err         =  ..\Produtos
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas
tab 	    = ..\Tabelas
inc 	    = ..\Tabelas 

[Modulos]
testelistacircular
lista_circular

[BuildInicio]
/OUT:..\produtos\TesteCircular.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib


[Fim]
